"use client";

import { Camera, Check, ImagePlus, Loader2, Star, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";
import { useMemo, useState } from "react";
import type { Product } from "@/lib/types";
import { slugify } from "@/lib/utils";

type Photo={url:string;file?:File};

export function ProductForm({product}:{product?:Product}) {
  const router=useRouter();const [photos,setPhotos]=useState<Photo[]>((product?.images||[]).map(url=>({url})));const [primary,setPrimary]=useState(product?.primary_image||0);const [loading,setLoading]=useState(false);const [toast,setToast]=useState("");const [error,setError]=useState("");
  const title=product?"Editar celular":"Adicionar celular";
  function addFiles(list:FileList|null){if(!list)return;const incoming=[...list].filter(file=>file.type.startsWith("image/")).slice(0,12-photos.length).map(file=>({file,url:URL.createObjectURL(file)}));setPhotos(current=>[...current,...incoming])}
  function removePhoto(index:number){setPhotos(current=>current.filter((_,i)=>i!==index));setPrimary(current=>current===index?0:current>index?current-1:current)}
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setLoading(true);setError("");const data=new FormData(event.currentTarget);try{const newFiles=photos.filter(p=>p.file).map(p=>p.file as File);let uploaded:string[]=[];if(newFiles.length){const form=new FormData();newFiles.forEach(file=>form.append("files",file));const upload=await fetch("/api/admin/upload",{method:"POST",body:form});const result=await upload.json();if(!upload.ok)throw new Error(result.error);uploaded=result.urls}let cursor=0;const images=photos.map(photo=>photo.file?uploaded[cursor++]:photo.url);if(!images.length)throw new Error("Adicione pelo menos uma foto.");const payload={brand:data.get("brand"),model:data.get("model"),storage:data.get("storage"),color:data.get("color"),condition:data.get("condition"),price:Number(data.get("price")),stock:Number(data.get("stock")),battery_health:data.get("battery_health")?Number(data.get("battery_health")):null,warranty:data.get("warranty"),description:data.get("description"),images,primary_image:Math.min(primary,images.length-1),featured:data.get("featured")==="on",hidden:data.get("hidden")==="on",slug:slugify(`${data.get("model")} ${data.get("storage")}`)};const response=await fetch(product?`/api/admin/products/${product.id}`:"/api/admin/products",{method:product?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const result=await response.json();if(!response.ok)throw new Error(result.error);setToast(product?"Alterações salvas com sucesso.":"Celular publicado na vitrine.");setTimeout(()=>{router.push("/admin/produtos");router.refresh()},900)}catch(err){setError(err instanceof Error?err.message:"Não foi possível salvar.");setLoading(false)}}
  const defaults=useMemo(()=>({brand:product?.brand||"Apple",model:product?.model||"",storage:product?.storage||"128GB",color:product?.color||"",condition:product?.condition||"Seminovo",price:product?.price||"",stock:product?.stock??1,battery:product?.battery_health||"",warranty:product?.warranty||"90 dias",description:product?.description||""}),[product]);
  return <><header className="admin-topbar"><div><h1>{title}</h1><p>{product?"Atualize as informações e salve.":"Tire as fotos, preencha os dados e publique."}</p></div></header><form className="product-form" onSubmit={submit}>
    <section className="form-section full"><h2>1. Fotos do aparelho</h2><p className="demo-note">Adicione até 12 fotos. Toque na estrela para escolher a principal.</p><div className="upload-zone"><div className="upload-actions"><label className="button button-primary"><Camera size={18}/> Tirar foto<input hidden type="file" accept="image/*" capture="environment" onChange={e=>{addFiles(e.target.files);e.target.value=""}}/></label><label className="button button-soft"><ImagePlus size={18}/> Escolher da galeria<input hidden type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={e=>{addFiles(e.target.files);e.target.value=""}}/></label></div><div className="upload-preview-grid">{photos.map((photo,index)=><div className={`upload-preview ${primary===index?"primary":""}`} key={photo.url}><img src={photo.url} alt={`Foto ${index+1}`}/><div className="upload-preview-actions"><button type="button" onClick={()=>setPrimary(index)} aria-label="Definir como principal"><Star size={15} fill={primary===index?"#176bff":"none"}/></button><button type="button" onClick={()=>removePhoto(index)} aria-label="Remover foto"><Trash2 size={15}/></button></div></div>)}</div></div></section>
    <section className="form-section"><h2>2. Informações</h2><div className="form-grid"><label className="field">Marca<select name="brand" defaultValue={defaults.brand} required><option>Apple</option><option>Samsung</option><option>Motorola</option><option>Xiaomi</option><option>Outra</option></select></label><label className="field">Modelo<input name="model" defaultValue={defaults.model} required placeholder="Ex.: iPhone 13"/></label><label className="field">Armazenamento<select name="storage" defaultValue={defaults.storage}><option>64GB</option><option>128GB</option><option>256GB</option><option>512GB</option><option>1TB</option></select></label><label className="field">Cor<input name="color" defaultValue={defaults.color} required placeholder="Ex.: Meia-noite"/></label><label className="field">Condição<select name="condition" defaultValue={defaults.condition}><option>Novo</option><option>Seminovo</option></select></label><label className="field">Saúde da bateria (%)<input name="battery_health" type="number" min="0" max="100" defaultValue={defaults.battery}/></label><label className="field">Garantia<input name="warranty" defaultValue={defaults.warranty} required/></label><label className="field wide">Descrição<textarea name="description" rows={5} defaultValue={defaults.description} required placeholder="Descreva o estado, diferenciais e observações do aparelho."/></label></div></section>
    <section className="form-section"><h2>3. Preço e estoque</h2><div className="form-grid"><label className="field">Preço (R$)<input name="price" type="number" min="0" step="0.01" defaultValue={defaults.price} required/></label><label className="field">Estoque<input name="stock" type="number" min="0" step="1" defaultValue={defaults.stock} required/></label><label className="check-option wide"><input type="checkbox" name="featured" defaultChecked={product?.featured}/> Mostrar nos destaques da Home</label><label className="check-option wide"><input type="checkbox" name="hidden" defaultChecked={product?.hidden}/> Manter oculto da vitrine</label></div><p className="demo-note">Ao chegar a zero, o produto será ocultado automaticamente e continuará salvo no painel.</p></section>
    {error&&<p className="form-error" role="alert">{error}</p>}<div className="form-submit"><button type="button" className="button button-soft" onClick={()=>router.back()}>Cancelar</button><button className="button button-primary button-lg" disabled={loading}>{loading?<><Loader2 className="spin"/>Salvando...</>:<><Check/> {product?"Salvar alterações":"Publicar celular"}</>}</button></div>
  </form>{toast&&<div className="toast" role="status">{toast}</div>}</>;
}
