"use client";

import { Eye, EyeOff, Pencil, Plus, Trash2 } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import type { Product } from "@/lib/types";
import { formatCurrency } from "@/lib/utils";

export function ProductsManager({ initialProducts }: { initialProducts: Product[] }) {
  const [products,setProducts]=useState(initialProducts);const [remove,setRemove]=useState<Product|null>(null);const [toast,setToast]=useState("");
  async function toggle(product:Product){const response=await fetch(`/api/admin/products/${product.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({hidden:!product.hidden})});const data=await response.json();if(!response.ok)return setToast(data.error);setProducts(items=>items.map(item=>item.id===product.id?data:item));setToast(product.hidden?"Produto reativado.":"Produto ocultado.");setTimeout(()=>setToast(""),2500)}
  async function confirmDelete(){if(!remove)return;const response=await fetch(`/api/admin/products/${remove.id}`,{method:"DELETE"});const data=await response.json();if(!response.ok){setToast(data.error);return}setProducts(items=>items.filter(item=>item.id!==remove.id));setRemove(null);setToast("Produto excluído.");setTimeout(()=>setToast(""),2500)}
  return <><header className="admin-topbar"><div><h1>Produtos</h1><p>Gerencie os aparelhos da vitrine.</p></div><Link className="button button-primary" href="/admin/produtos/novo"><Plus size={18}/><span>Adicionar produto</span></Link></header><section className="admin-card"><div className="table-wrap"><table className="admin-table"><thead><tr><th>Produto</th><th>Categoria</th><th>Marca</th><th>Preço</th><th>Condição</th><th>Estoque</th><th>Status</th><th>Ações</th></tr></thead><tbody>{products.map(product=><tr key={product.id}><td><div className="table-product"><img src={product.images[product.primary_image]||product.images[0]} alt=""/><b>{product.model}<small style={{display:"block",color:"#7c8798"}}>{product.storage}</small></b></div></td><td>{product.category}</td><td>{product.brand}</td><td>{formatCurrency(product.price)}</td><td>{product.condition}</td><td>{product.stock}</td><td><span className={`status-pill ${product.stock===0?"out":product.hidden?"hidden":""}`}>{product.stock===0?"Sem estoque":product.hidden?"Oculto":"Ativo"}</span></td><td><div className="actions-cell"><Link className="icon-button" href={`/admin/produtos/${product.id}/editar`} title="Editar"><Pencil size={16}/></Link><button className="icon-button" onClick={()=>toggle(product)} title={product.hidden?"Reativar":"Ocultar"}>{product.hidden?<Eye size={16}/>:<EyeOff size={16}/>}</button><button className="icon-button danger" onClick={()=>setRemove(product)} title="Excluir"><Trash2 size={16}/></button></div></td></tr>)}</tbody></table></div>{!products.length&&<div className="empty-state"><h3>Nenhum produto cadastrado</h3><p>Adicione seu primeiro produto para começar.</p></div>}</section>{remove&&<div className="modal-backdrop" role="dialog" aria-modal="true"><div className="modal"><h3>Tem certeza que deseja excluir este produto?</h3><p>{remove.model} será removido permanentemente. Para apenas tirar da vitrine, use “Ocultar”.</p><div className="modal-actions"><button className="button button-soft" onClick={()=>setRemove(null)}>Cancelar</button><button className="button button-danger" onClick={confirmDelete}>Excluir produto</button></div></div></div>}{toast&&<div className="toast" role="status">{toast}</div>}</>;
}
